from selenium.webdriver.common.by import By


class UrbanRoutesLocators:
    from_field = (By.ID, 'from')
    to_field = (By.ID, 'to')
    map = (By.CLASS_NAME, 'gm-style')
    ask_button_taxi = (By.XPATH, ".//div[@class='results-text']/button[text()='Pedir un taxi']")
    rate_comfort = (By.XPATH, "//div[@class='tcard-title' and text()='Comfort']")
    phone_number_input = (By.CLASS_NAME, 'np-text')
    modal_phone_number_input = (By.ID, 'phone')
    next_button_modal_phone = (By.XPATH, "//button[@type='submit'][@class='button full']")
    entry_sms_code = (By.ID, 'code')
    confirm_sms_button = (By.XPATH, "//button[@class='button full' and text()='Confirmar']")
    payment_method_link = (By.CLASS_NAME, 'pp-value-text')
    add_card_modal_button = (By.CLASS_NAME, "pp-plus")
    card_number_entry = (By.ID, 'number')
    card_cvv_entry = (By.CSS_SELECTOR, "input[placeholder='12']")
    card_form_blank_space = (By.CLASS_NAME, 'card-wrapper')
    add_card_button_link = (By.XPATH, "//button[@type='submit'][@class='button full' and text()='Enlace']")
    close_add_card_modal_button = (By.XPATH, '//*[@id="root"]/div/div[2]/div[2]/div[1]/button')
    entry_driver_comment = (By.ID, 'comment')
    reqst_blank = (By.XPATH, "//*[@id='root']/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[1]/div/div[2]/div/span")
    chk_blk_ts = (By.XPATH, "//*[@id='root']/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[1]/div/div[2]/div/input")
    label_blanket_tissue = (By.XPATH, "//div[contains(text(),'Manta y pañuelos')]")
    reqst_two_icecream = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[3]/div/div[2]/div[1]/div/div[2]/div/div[3]')
    count_two_icecream = (By.XPATH, '//*[@id="root"]/div/div[3]/div[3]/div[2]/div[2]/div[4]/div[2]/div[3]/div/div[2]/div[1]/div/div[2]/div/div[2]')
    button_order_a_taxi_final = (By.CLASS_NAME, 'smart-button')
    route_details_button = (By.XPATH, "//button[@class='order-button' and img[@alt='burger']]")
    route_details_form = (By.CLASS_NAME, 'order-body')
    label_searching_taxi_form = (By.XPATH, "//div[@class='order-header-title' and text()='Buscar automóvil']")
    label_driver_name = (By.XPATH, '//*[@id="root"]/div/div[5]/div[2]/div[2]/div[1]/div[1]/div[2]')
    label_vehicle_plate = (By.XPATH, "//div[@class='number']")
    waiting_vehicle_minutes_label = (By.XPATH, "//div[@class='order-header-title']")
